name: Build plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: logseq-md-convert
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Build
        id: build
        run: |
          pnpm install
          pnpm build
          mkdir ${{ env.PLUGIN_NAME }}
          cp readme.md package.json manifest.json logo.svg ${{ env.PLUGIN_NAME }}
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          prerelease: false
          artifacts: "${{ env.PLUGIN_NAME }}.zip,package.json"
          token: ${{ secrets.GITHUB_TOKEN }}
